# NON-SECRET config for UAT. Never put a secret here.
variables:
  - name: azureSubscription
    value: "<AZU-EUR-FR-UAT-APPSPN>"
  - name: appName
    value: "<WAS-EUR-FR-UAT-WEB-APP>"
  - name: rgName
    value: "<RG-EUR-FR-UAT-APP>"
  - name: environment
    value: uat
